version: 0.2

phases:
  install:
    commands:
      - echo Installing source NPM dependencies...
  pre_build:
    commands:
      - echo Installing client NPM dependencies...
      - cd client
      - npm install
      - cd ..
      - echo Installing server NPM dependencies...
      - cd server
      - npm install
      - cd ..
  build:
    commands:
      - echo Build started on `date`
      - echo Building the client...
      - npm run install:client
      - npm run build:client
      - echo Building the server...
      - npm run install:server
  post_build:
    commands:
      - echo Deployment started on `date`
      - echo Serving the build folder...
      - npm install -g serve
      - serve -s client/build -l 3000 & serve -s server/build -l 5000
artifacts:
  files:
    - '**/*'
  base-directory: './'
